import React from 'react';
import Header from './Header';
import Head from 'next/head';
import Footer from './Footer';
import react, { useState } from 'react';
import Userorders from './Userorders'
import User_Profile from './user_profile'
import Your_order from './your_orders'
import Your_orders from './your_orders';


function Accounts() {

  const [userOrders , setuserOrders] = useState();



    return (
        <>

        <Head>
          <title>Food Port</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
        </Head>

      <Header />

     <div className='container-fluid fstcon'>
     <img className='logimgs' src="img/logologo.f87723ea.png" alt="food port"/>
     <p className='acntpg'>Account Page</p>
     <div className='row'>
     <div className='col'>
     <img className='bckimg' src="img/form_Banner.jpg" alt="food port"/>
     </div>

     </div>

     <div className='row fusro'>
     <div className='col-3 fstconso'>
     <p className='totex'  onClick={()=>setuserOrders("ghi")}>Accounts</p>
     <p className='totexs'>You can check your account here</p>
     </div>

     <div className='col-3 fstconso'>
     <p className='totex'  onClick={()=>setuserOrders("def")}>Profile</p>
     <p className='totexs'>You can check your profile here</p>
     </div>
     <div className='col-3 fstconso'>
     <p className='totex' onClick={()=>setuserOrders("abc")}>Orders</p>
     <p className='totexs'>you can check your orders here</p>
     </div>
    
     </div>
     {userOrders === "abc" &&
     <Userorders/>
    }
    {userOrders === "def" &&
    <User_Profile/>
   }
   {userOrders === "ghi" &&
   <Your_orders/>
  }

     </div>

      <Footer />
      </>
    )
}

export default Accounts
